#São operadores utilizados em conjunto com operadores de comparação para montar uma expressão lógica.
#Quando um operador de comparação é utilizado, o resultado retornado é um booleano, dessa forma podemos combinar operadores de comparação com os operadores lógicos.
    #Ex: op_comparacao + op_logico + op_comparacao ... N ...